# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print("memory size :",a.size*a.itemsize)

memory size : 80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a=np.zeros(10)
a[4]=1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a=np.arange(10)
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a=[1,2,0,0,4,0]
print(np.nonzero(a))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
a=np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a=np.random.random(27).reshape(3,3,3)
print(a)

[[[0.64200614 0.19758184 0.94606381]
  [0.59741888 0.12450668 0.13767371]
  [0.65466607 0.92381327 0.73401545]]

 [[0.86165569 0.26550742 0.59895377]
  [0.46598533 0.18888175 0.41714262]
  [0.53439862 0.55042892 0.56063615]]

 [[0.93029816 0.83457083 0.6060538 ]
  [0.16398672 0.99442799 0.23169954]
  [0.16914189 0.05874973 0.72838066]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.random(100).reshape(10,10)
print("min :",np.min(a),"max :",np.max(a))

min : 0.01298202376385349 max : 0.9677561333064859


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.random(30)
print(np.mean(a))

0.534049234471895


0.534049234471895

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones((5,5),dtype=int)
a[1:-1,1:-1]=0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


2

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.ones((2,2))
a=np.pad(a,pad_width=1,mode="constant",constant_values=0)
a

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False

nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
a=np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a=np.array([[0,1],[0,1]])
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
a=np.random.random((5,5))
z=(a-a.min())/(a.max()-a.min())
print(z)

[[0.04240395 0.32812733 0.53248655 0.62874949 0.43448156]
 [0.62392783 0.98184518 1.         0.12042213 0.08230226]
 [0.16212753 0.23007175 0.36767455 0.31880305 0.        ]
 [0.15410085 0.53476559 0.90136857 0.15505101 0.9690265 ]
 [0.32201071 0.45633288 0.93206871 0.68699125 0.23998674]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("R", np.ubyte, (1,)),
                  ("G", np.ubyte, (1,)),
                  ("B", np.ubyte, (1,)),
                  ("A", np.ubyte, (1,))])
color

dtype([('R', 'u1', (1,)), ('G', 'u1', (1,)), ('B', 'u1', (1,)), ('A', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.ones((5,3),dtype=int)
b=np.ones((3,2),dtype=int)
c=np.dot(a,b)
c

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a=np.arange(11)
a[(a>=3)&(a<=8)]=-1
print(a)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(a)), a))


[  9.  -6.   3.  -4. -10.   2.  -9.  -6.  -7.   3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a=np.random.randint(0,10,10)
b=np.random.randint(5,10,10)
print(np.intersect1d(a,b))

[5 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all="ignore")
np.ones(3)/0

array([inf, inf, inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today=np.datetime64('today','D')
yesterday=today - np.timedelta64(1,'D')
tomorrow=today + np.timedelta64(1,'D')
print(f"today {today} yesterday {yesterday} tomorrow {tomorrow}")

today 2022-02-12 yesterday 2022-02-11 tomorrow 2022-02-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange('2021-07','2021-08',dtype='datetime64[D]'))

['2021-07-01' '2021-07-02' '2021-07-03' '2021-07-04' '2021-07-05'
 '2021-07-06' '2021-07-07' '2021-07-08' '2021-07-09' '2021-07-10'
 '2021-07-11' '2021-07-12' '2021-07-13' '2021-07-14' '2021-07-15'
 '2021-07-16' '2021-07-17' '2021-07-18' '2021-07-19' '2021-07-20'
 '2021-07-21' '2021-07-22' '2021-07-23' '2021-07-24' '2021-07-25'
 '2021-07-26' '2021-07-27' '2021-07-28' '2021-07-29' '2021-07-30'
 '2021-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a=np.zeros((5,5),dtype=int)
a+=np.arange(5)
a


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def gen_func():
  for i in range(10):
    yield i
print(np.fromiter(gen_func(),dtype=int,count=-1))

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
print(np.linspace(start=0,stop=1,num=10,endpoint=False))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a=np.random.randint(10,size=10)
a.sort()
print(a)

[1 1 2 3 4 7 8 9 9 9]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a=np.arange(10)
b=np.add.reduce(a)
print(b)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a=np.arange(10)
b=np.arange(10)
print(np.array_equal(a,b))

True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
a=np.ones(10)
a.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a=np.random.random((5,2))
x=a[:,0]
y=a[:,1]
radius=np.sqrt(x**2+y**2)
theta=np.arctan(y/x)#tan inverse==arctan
print(f"radius : {radius}, theta : {theta}")

radius : [0.96218499 0.8959971  1.17080652 1.01452232 0.53181007], theta : [0.42713186 0.00258476 0.97329691 0.75746623 0.30905207]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a=np.random.randint(20,50,10)
print(a)
a[np.argmax(a)]=0
print("modified a :",a)



[24 35 20 34 35 46 26 27 44 47]
modified a : [24 35 20 34 35 46 26 27 44  0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
a = np.zeros((5, 5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(a)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
a=np.random.random((5,5))
b=np.random.random((5,5))
c=1/(np.subtract.outer(a,b))
print(np.linalg.det(c))

[[ 8.72241922e+04  3.21901673e+04 -9.54269042e+04  2.21842989e+04
  -2.86700703e+03]
 [-3.45051306e+04  2.68454070e+07 -9.91166461e+04 -5.51432156e+05
  -2.89071305e+06]
 [ 1.70214668e+05 -5.36778742e+03  4.88685215e+04 -5.77150506e+04
   5.57478852e+05]
 [-1.39858698e+08  2.98025560e+04 -1.58677671e+05 -3.30326906e+04
  -2.33818370e+05]
 [-2.48905215e+05 -1.91358150e+05  7.37795610e+05 -9.50528071e+05
  -5.18134478e+04]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
a=[np.int32,np.int64]
for i in a:
  print(f"min of {i} is {np.iinfo(i).min}")
  print(f"max of {i} is {np.iinfo(i).max}")
print(" ")
b=[np.float32,np.float64]
for i in b:
  print(f"min of {i} is {np.finfo(i).min}")
  print(f"max of {i} is {np.finfo(i).max}")


min of <class 'numpy.int32'> is -2147483648
max of <class 'numpy.int32'> is 2147483647
min of <class 'numpy.int64'> is -9223372036854775808
max of <class 'numpy.int64'> is 9223372036854775807
 
min of <class 'numpy.float32'> is -3.4028234663852886e+38
max of <class 'numpy.float32'> is 3.4028234663852886e+38
min of <class 'numpy.float64'> is -1.7976931348623157e+308
max of <class 'numpy.float64'> is 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a=np.arange(10)
b=np.random.uniform(0,10)
i=np.abs(a-b).argmin()
print(a[i])



4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a= np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a=np.random.random((100,2))
b=np.atleast_2d(a[:,0])
c=np.atleast_2d(a[:,1])
d=np.sqrt((b-b.T)**2 + (c-c.T)**2)
print(d)

[[0.         0.22360135 0.23621747 ... 0.85711094 0.27236733 0.34223719]
 [0.22360135 0.         0.45944549 ... 0.92285474 0.49389598 0.46560282]
 [0.23621747 0.45944549 0.         ... 0.82930738 0.07602286 0.32911009]
 ...
 [0.85711094 0.92285474 0.82930738 ... 0.         0.90143058 0.5216334 ]
 [0.27236733 0.49389598 0.07602286 ... 0.90143058 0.         0.40505066]
 [0.34223719 0.46560282 0.32911009 ... 0.5216334  0.40505066 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a=(np.random.rand(10)*100).astype(np.float32)
b=a.view(np.int32)
print(b)

[1317373992 1317340856 1317316264 1317152461 1317183194 1317289121
 1317276897 1317330966 1317317634 1317359892]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
a=StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")
b=np.genfromtxt(a,delimiter=",",dtype=int)
print(b)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a=np.arange(9).reshape(3,3)
for i,j in np.ndenumerate(a):
  print(i,j)
print(" ")
for i in np.ndindex(a.shape):
  print(i,a[i])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
a,b= np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
c= np.sqrt(a*a+b*b)
sigma, mu = 1.0, 0.0
d= np.exp(-( (c-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(d)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
p = 3
a= np.zeros((10,10))
np.put(a, np.random.choice(range(10*10), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
a=np.random.rand(5,10)
b=a-a.mean(axis=1,keepdims=True)
print(b)

[[ 0.18903134  0.29727751 -0.36637053 -0.00613364 -0.08163708  0.43939199
  -0.41760511 -0.10945562  0.01260139  0.04289975]
 [ 0.22196223 -0.12001762 -0.50294298  0.16678998 -0.30349917  0.43486969
   0.20818794  0.35497893 -0.34506056 -0.11526845]
 [ 0.11147904 -0.5138559  -0.56755961 -0.11348854  0.26958203  0.22071443
   0.13290988 -0.16106373  0.33746118  0.28382123]
 [ 0.3568916  -0.10011714  0.34380954  0.32477814 -0.32060245 -0.24668009
  -0.27713972 -0.31406163  0.15140641  0.08171535]
 [-0.49419741  0.05173425  0.3740313  -0.17464764 -0.1646214   0.40372163
  -0.07929245  0.11916094  0.40145385 -0.43734307]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
a=np.random.randint(1,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[1 4 4]
 [2 2 1]
 [4 4 7]]
[[2 2 1]
 [1 4 4]
 [4 4 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a=np.random.randint(0,3,(3,10))
b=(~a.any(axis=0).any())
print(b)

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
a = np.random.uniform(0,1,10)
b = 0.5
c = a.flat[np.abs(a - b).argmin()]
print(c)

0.5300534289853568


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
c = np.nditer([a,b,None])
for i,j,k in c: 
  k[...] = i + j
print(a,b)
print(c.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[7. 5. 3. 3. 1. 3. 5. 9. 7. 7.]
[1 7 3 7 8 9 9 2 0 8 1 0 6 7 0 9 8 6 7 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a=np.random.randint(0,5,5)
b=np.random.randint(5,10,5)
c=np.bincount(b,a)
print(c)

[0. 0. 0. 0. 0. 0. 0. 6. 0. 8.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h=256,256
a=np.random.randint(0,4,(w,h,3),dtype=np.uint8)
b=np.dot(a.astype(np.uint32),[1,256,65536])
c=len(np.unique(b))
print(c)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
a= np.random.randint(0,10,(3,4,3,4))
b = a.sum(axis=(-2,-1))
print(b)

[[77 55 47 66]
 [60 48 73 60]
 [74 60 59 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
a = np.random.uniform(0,1,100)
b = np.random.randint(0,10,100)
a_sums = np.bincount(b, weights=a)
a_counts = np.bincount(b)
a_means = a_sums / a_counts
print(a_means)

[0.33771757 0.52347848 0.5842827  0.48786321 0.45007295 0.58054922
 0.7038185  0.53806104 0.55952663 0.46716929]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a = np.random.uniform(0,1,(3,3))
b = np.random.uniform(0,1,(3,3))
c=np.diag(np.dot(a,b))
print(c)

[0.60668397 0.52190206 0.94743109]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
a = np.array([1,2,3,4,5])
n = 3
b = np.zeros(len(a) + (len(a)-1)*(n))
b[::n+1] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a = np.ones((5,5,3))
b = 3*np.ones((5,5))
print(a * b[:,:,None])

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a = np.arange(9).reshape(3,3)
a[[0,1]] = a[[1,0]]
print(a)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
tri = np.random.randint(0,20,(10,3))
a = np.roll(tri.repeat(2,axis=1),-1,axis=1)
a = a.reshape(len(a)*3,2)
a = np.sort(a,axis=1)
b = a.view( dtype=[('i',a.dtype),('j',a.dtype)] )
b = np.unique(b)
print(b)

[( 0,  2) ( 0,  4) ( 0,  7) ( 0, 11) ( 1,  6) ( 1, 10) ( 1, 14) ( 1, 17)
 ( 2,  3) ( 2, 11) ( 2, 12) ( 3, 12) ( 4,  7) ( 5,  7) ( 5, 18) ( 6,  8)
 ( 6,  9) ( 6, 10) ( 7, 18) ( 8,  9) ( 8, 17) ( 9, 17) (10, 13) (10, 14)
 (13, 14) (14, 15) (14, 17) (14, 19) (15, 19)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
a=np.arange(20)
n=3
b=np.cumsum(a,dtype=float)
b[n:]=b[n:]-b[:-n]
c=b[n-1:]/n
print(c)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

In [ ]:
from numpy.lib import stride_tricks
a=np.arange(10)
w=3
shape=(a.size-w+1,w)
stride=(a.strides[0],a.strides[0])
print(stride_tricks.as_strided(a, shape=shape, strides=stride))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [4]:
a = np.random.randint(0,2,100)
b=np.logical_not(a, out=a)
print(b)

[0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 0 0 1
 1 1 0 0 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 1 0 0 1 1 0
 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1]


In [11]:
a= np.random.uniform(-1.0,1.0,100)
print(np.negative(a, out=a))


[ 0.52941295  0.81803757 -0.01756783  0.98750798 -0.8300565  -0.63304084
 -0.73108244  0.83202085  0.61996367 -0.0635965  -0.48525477 -0.48486437
  0.24143145  0.35343969 -0.54817147 -0.52215058 -0.91813168  0.78727875
  0.46240364  0.00990939 -0.48866022  0.03747463 -0.32527436 -0.01450709
  0.66242935 -0.23668753  0.23878957  0.25644566  0.38198143  0.22161822
  0.08303417  0.2302033  -0.75575802 -0.67078913  0.07841228 -0.05782368
 -0.64743709  0.34880668  0.51926093 -0.63678426 -0.92795438  0.44654081
  0.36596194  0.2777334   0.80775453 -0.92170435  0.82833793  0.23169339
  0.17244218  0.50439887  0.27156708  0.35624936  0.8634112   0.18613789
 -0.97896992  0.34780979  0.09429134  0.14469528 -0.67742193  0.08136246
 -0.73922385 -0.07245864 -0.98516062 -0.79139823  0.97714868 -0.5810724
  0.13009593 -0.36164606  0.49793525  0.8080838   0.38581603 -0.08631749
 -0.88410143 -0.34301726 -0.551994    0.52396545  0.74103294 -0.42906263
 -0.58526804 -0.29093386  0.28575235 -0.48720707 -0.

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [15]:
d=np.random.uniform(10,10,(10,2))
d0=np.random.uniform(-10,10,(10,2))
d1=np.random.uniform(-10,10,(10,2))
a=d1-d0
b=(a**2).sum(axis=1)
c=-((d0[:,0]-d[...,0])*a[:,0]+(d0[:,1]-d[...,1])*a[:,1]) / b
c=c.reshape(len(c),1)
print(np.sqrt(((d0+c*a-d)**2).sum(axis=1)))

[16.05023996  9.74877904  4.2168395   0.49153277  8.69505323  6.24945999
  5.47376953  2.71662158 18.61204666  2.00273497]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [16]:
d = np.random.uniform(-10, 10, (10,2))
d0 = np.random.uniform(-10,10,(10,2))
d1 = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(d0,d1,i) for i in d]))

[[ 2.01897117  2.21524787  9.54881987  2.90798151  7.1929396   9.38669716
   7.42444251 13.12673023 10.40395023 14.60080161]
 [16.04157546  6.3245469   9.01009719  3.82357784  7.76121147  8.17179616
  11.52344087  5.22236018  7.52818694  1.2631461 ]
 [ 2.07779867  4.75281544  9.25376053  6.31261957  3.86626377  5.96882416
   6.61658667 11.26893054 10.53727    11.89575893]
 [ 2.62697025  1.64419572  5.01019257  0.88605225  9.54173303 11.34104615
   3.12631014  9.67690122  5.74141493 12.34617093]
 [ 6.9472611   6.91666583  1.02817107  3.2799946  13.95619348 15.45378168
   0.2872383   7.75519262  1.35544311 12.09878812]
 [13.72829523  8.01945683  6.2379558   0.08009647 11.38282609 12.12959618
   8.13027376  0.74140432  5.31459133  3.8319262 ]
 [15.24988555  1.21398648  8.86745331 10.21404949  1.46193957  1.76762889
  12.33384876  8.03671142  6.60076035  5.77001245]
 [ 5.70493679  6.86073259  0.43639636 14.565741    3.5564812   2.44604539
   3.55391289  1.06039043  2.9826261   1.29787533]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [19]:
a = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

b = np.ones(shape, dtype=a.dtype)*fill
c  = np.array(list(position)).astype(int)
b_s = np.array(list(b.shape)).astype(int)
a_s = np.array(list(a.shape)).astype(int)

b_start = np.zeros((len(shape),)).astype(int)
b_stop  = np.array(list(shape)).astype(int)
a_start = (c-b_s//2)
a_stop  = (c+b_s//2)+b_s%2

b_start = (b_start - np.minimum(a_start,0)).tolist()
a_start = (np.maximum(a_start,0)).tolist()
b_stop = np.maximum(b_start, (b_stop - np.maximum(a_stop-a_s,0))).tolist()
a_stop = (np.minimum(a_stop,a_s)).tolist()

u = [slice(start,stop) for start,stop in zip(b_start,b_stop)]
v = [slice(start,stop) for start,stop in zip(a_start,a_stop)]
b[u] = a[v]
print(a)
print(b)

[[6 6 7 9 0 7 4 6 0 0]
 [9 8 5 1 0 4 8 6 5 5]
 [4 3 9 6 0 2 1 3 2 1]
 [6 3 6 0 0 1 5 7 1 8]
 [6 5 9 3 8 6 1 9 4 9]
 [7 5 4 4 7 9 8 4 2 1]
 [8 5 5 3 3 9 3 9 4 8]
 [4 4 5 3 5 6 3 4 6 1]
 [8 6 8 5 8 3 9 7 8 1]
 [8 6 0 1 4 7 2 0 4 4]]
[[0 0 0 0 0]
 [0 6 6 7 9]
 [0 9 8 5 1]
 [0 4 3 9 6]
 [0 6 3 6 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [26]:
from numpy.lib import stride_tricks
a = np.arange(1,15,dtype=np.uint32)
b = stride_tricks.as_strided(a,(11,4),(4,4))
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [3]:
a = np.random.uniform(0,1,(10,10))
x, y, z = np.linalg.svd(a)
rank = np.sum(y > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [8]:
a= np.random.randint(0,10,100)
print(np.bincount(a).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [10]:
from numpy.lib import stride_tricks
a = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (a.shape[0]-3)
j = 1 + (a.shape[1]-3)
b = stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(b)

[[[[0 4 4]
   [1 3 4]
   [1 3 1]]

  [[4 4 0]
   [3 4 3]
   [3 1 4]]

  [[4 0 4]
   [4 3 0]
   [1 4 0]]

  [[0 4 2]
   [3 0 2]
   [4 0 1]]

  [[4 2 3]
   [0 2 2]
   [0 1 2]]

  [[2 3 1]
   [2 2 4]
   [1 2 4]]

  [[3 1 2]
   [2 4 3]
   [2 4 3]]

  [[1 2 2]
   [4 3 2]
   [4 3 3]]]


 [[[1 3 4]
   [1 3 1]
   [3 0 1]]

  [[3 4 3]
   [3 1 4]
   [0 1 2]]

  [[4 3 0]
   [1 4 0]
   [1 2 2]]

  [[3 0 2]
   [4 0 1]
   [2 2 3]]

  [[0 2 2]
   [0 1 2]
   [2 3 1]]

  [[2 2 4]
   [1 2 4]
   [3 1 3]]

  [[2 4 3]
   [2 4 3]
   [1 3 0]]

  [[4 3 2]
   [4 3 3]
   [3 0 1]]]


 [[[1 3 1]
   [3 0 1]
   [2 0 4]]

  [[3 1 4]
   [0 1 2]
   [0 4 1]]

  [[1 4 0]
   [1 2 2]
   [4 1 1]]

  [[4 0 1]
   [2 2 3]
   [1 1 3]]

  [[0 1 2]
   [2 3 1]
   [1 3 1]]

  [[1 2 4]
   [3 1 3]
   [3 1 2]]

  [[2 4 3]
   [1 3 0]
   [1 2 2]]

  [[4 3 3]
   [3 0 1]
   [2 2 3]]]


 [[[3 0 1]
   [2 0 4]
   [3 0 4]]

  [[0 1 2]
   [0 4 1]
   [0 4 2]]

  [[1 2 2]
   [4 1 1]
   [4 2 3]]

  [[2 2 3]
   [1 1 3]
   [2 3 3]]

  [[2 3 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [11]:
p, n = 10, 20
a = np.ones((p,n,n))
b = np.ones((p,n,1))
c = np.tensordot(a, b, axes=[[0, 2], [0, 1]])
print(c)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [12]:
a = np.ones((16,16))
k = 4
b = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print(b)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
a = np.random.rand(10000)
n = 10
print(a[np.argsort(a)[-n:]])

[0.99915181 0.99915863 0.99919359 0.99919673 0.99929919 0.99934942
 0.9994301  0.99950047 0.99959428 0.99976282]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
a=([1,2],[4,5,6],[7,8,9])
b=[np.asarray(i) for i in a]
shape=(len(i) for i in b)
index=np.indices(shape,dtype=int)
index=index.reshape(len(b),-1).T
for i,j in enumerate(b):
  index[:,i] = b[i][index[:,i]]
print(index)


[[1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [1 6 7]
 [1 6 8]
 [1 6 9]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [2 6 7]
 [2 6 8]
 [2 6 9]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
a = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
b = np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(b)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
Z = np.random.rand(int(5e7))
a=np.power(Z,3)
b=Z*Z*Z
c=np.einsum('i,i,i->i',Z,Z,Z)
print(a,b,c)

[0.0145325  0.98394237 0.0412222  ... 0.53752947 0.95350265 0.64885466] [0.0145325  0.98394237 0.0412222  ... 0.53752947 0.95350265 0.64885466] [0.0145325  0.98394237 0.0412222  ... 0.53752947 0.95350265 0.64885466]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
a = np.random.randint(0,5,(10,3))
b = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
c = a[~b]
print(a)
print(c)

[[1 2 4]
 [3 1 3]
 [3 4 1]
 [1 1 3]
 [4 1 1]
 [4 0 4]
 [0 2 3]
 [4 0 0]
 [3 3 2]
 [2 0 3]]
[[1 2 4]
 [3 1 3]
 [3 4 1]
 [1 1 3]
 [4 1 1]
 [4 0 4]
 [0 2 3]
 [4 0 0]
 [3 3 2]
 [2 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
a = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
b=np.unpackbits(a[:, np.newaxis], axis=1)
print(b)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
a= np.random.randint(0,2,(6,3))
b = np.ascontiguousarray(a).view(np.dtype((np.void, a.dtype.itemsize * a.shape[1])))
_, u = np.unique(b, return_index=True)
c = a[u]
print(c)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)
a_sum=np.einsum('i->',a)
mul=np.einsum('i,i->i', a,b)
inner=np.einsum('i,i', a,b) 
outer=np.einsum('i,j->ij', a,b)
print(f'a_sum :{a_sum}  mul : {mul} inner : {inner} outer : {outer}')

a_sum :4.118973722380966  mul : [0.11324891 0.02202649 0.08496635 0.00098692 0.48486243 0.15346128
 0.15310218 0.32892706 0.02445094 0.33064954] inner : 1.6966820830398313 outer : [[1.13248906e-01 1.01075686e-02 5.82801441e-02 4.34183687e-02
  1.70034171e-01 5.30115232e-02 7.50973151e-02 8.22648460e-02
  1.06414319e-01 1.17383266e-01]
 [2.46792853e-01 2.20264883e-02 1.27004521e-01 9.46176302e-02
  3.70539722e-01 1.15523103e-01 1.63652624e-01 1.79272161e-01
  2.31898870e-01 2.55802480e-01]
 [1.65105045e-01 1.47357765e-02 8.49663466e-02 6.32994346e-02
  2.47892014e-01 7.72852491e-02 1.09484021e-01 1.19933530e-01
  1.55140932e-01 1.71132508e-01]
 [2.57420103e-03 2.29749800e-04 1.32473515e-03 9.86919992e-04
  3.86495687e-03 1.20497692e-03 1.70699738e-03 1.86991874e-03
  2.41884764e-03 2.66817697e-03]
 [3.22935909e-01 2.88223258e-02 1.66189255e-01 1.23810029e-01
  4.84862428e-01 1.51165473e-01 2.14144406e-01 2.34583042e-01
  3.03446682e-01 3.34725278e-01]
 [3.27840450e-01 2.92600606e-02 1.6

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
a = np.arange(0, 10*np.pi, 0.1)
n = 1
x = n*a*np.cos(a)
y = n*a*np.sin(a)
b = (np.diff(x)**2 + np.diff(y)**2)**0.5
z = np.zeros_like(x)
z[1:] = np.cumsum(b)       
z_int = np.linspace(0, z.max(), 10)
x_int = np.interp(z_int, z, x) 
y_int = np.interp(z_int, z, y)
print(x_int,y_int,z_int)

[  0.          -6.432776    -7.91485383  12.68524401  -9.28619199
  -4.53222154  22.71635022 -22.84587094  -7.28126809  31.39601771] [  0.          -8.06088076  12.38931677 -12.8222377   18.68549988
 -22.89614131  11.80032104  15.57624336 -28.68172655  -0.50007209] [  0.          55.0099808  110.0199616  165.0299424  220.03992319
 275.04990399 330.05988479 385.06986559 440.07984639 495.08982719]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
a = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
u = np.logical_and.reduce(np.mod(a, 1) == 0, axis=-1)
u &= (a.sum(axis=-1) == n)
print(a[u])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
a = np.random.randn(100)
n= 1000
idx = np.random.randint(0, a.size, (n, a.size))
means = a[idx].mean(axis=1)
b = np.percentile(means, [2.5, 97.5])
print(b)

[-0.04929434  0.34242367]
